### ISSUE TITLE
Add character: <F> to font: <Carlos>

### ISSUE THREAD

**Issue by Bhaveshgupta00** [codewithnick/ascii-art#228] opened 2023-10-07 13:50 UTC
*Character* : <F>
*Font* : <Carlos>

**Comment by AdityaDhavale** [comment] 2023-10-07 14:51
@Bhaveshgupta00 
I would like to work on this issue , please assign me

**Comment by AnshumanMahato** [comment] 2023-10-07 16:52
@AdityaDhavale check the font files for missing characters. Then, check for any existing opened issues for that character. If no issues exist, open a new issue specifying the character and the font. I will assign that to you. 😊

**Comment by sachinkumar911** [comment] 2023-10-25 01:14
@Bhaveshgupta00  are you working on it??

**Comment by rishavr920** [comment] 2023-10-26 14:13
assign me i can do it

**Comment by sachinkumar911** [comment] 2023-10-27 05:02
@rishavr920  i am assigning it to you..

**Comment by AnshumanMahato** [comment] 2023-10-30 10:38
@Yordaniss, would you like to work on this?

**Comment by Yordaniss** [comment] 2023-10-30 10:44
> @Yordaniss, would you like to work on this?

@AnshumanMahato  yes, sure 🙂

**Comment by Yordaniss** [comment] 2023-10-30 15:33
@AnshumanMahato work is done. Please review the changes 🙂

**Comment by AnshumanMahato** [comment] 2023-10-30 16:15
@Yordaniss, everything works as intended. 😊

**Closed** 2023-10-30 16:14 UTC
Labels: up-for-grab
